<?php

use Illuminate\Database\Seeder;
use App\City;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['province_id' => '1','city_id' => '11', 'nama_cities' => 'Banda Aceh'],
            ['province_id' => '1','city_id' => '12', 'nama_cities' => 'Langsa'],
            ['province_id' => '1','city_id' => '13', 'nama_cities' => 'Lhokseumawe'],
            ['province_id' => '1','city_id' => '14', 'nama_cities' => 'Sabang'],
            ['province_id' => '1','city_id' => '105', 'nama_cities' => 'Subulussalam'],
            ['province_id' => '17','city_id' => '51', 'nama_cities' => 'Denpasar'],
            ['province_id' => '9','city_id' => '19', 'nama_cities' => 'Pangkal Pinang'],
            ['province_id' => '16','city_id' => '36', 'nama_cities' => 'Cilegon'],
            ['province_id' => '16','city_id' => '37', 'nama_cities' => 'Serang'],
            ['province_id' => '16','city_id' => '38', 'nama_cities' => 'Tangerang Selatan'],
            ['province_id' => '16','city_id' => '39', 'nama_cities' => 'Tangerang'],
            ['province_id' => '7','city_id' => '17', 'nama_cities' => 'Bengkulu'],
            ['province_id' => '14','city_id' => '34', 'nama_cities' => 'Yogyakarta'],
            ['province_id' => '29','city_id' => '75', 'nama_cities' => 'Gorontalo'],
            ['province_id' => '11','city_id' => '31', 'nama_cities' => 'Jakarta Barat'],
            ['province_id' => '11','city_id' => '30', 'nama_cities' => 'Jakarta Pusat'],
            ['province_id' => '11','city_id' => '29', 'nama_cities' => 'Jakarta Selatan'],
            ['province_id' => '11','city_id' => '28', 'nama_cities' => 'Jakarta Timur'],
            ['province_id' => '11','city_id' => '27', 'nama_cities' => 'Jakarta Utara'],
            ['province_id' => '5','city_id' => '15', 'nama_cities' => 'Sungai Penuh'],
            ['province_id' => '5','city_id' => '115', 'nama_cities' => 'Jambi'],
            ['province_id' => '12','city_id' => '32', 'nama_cities' => 'Bandung'],
            ['province_id' => '12','city_id' => '302', 'nama_cities' => 'Bekasi'],
            ['province_id' => '12','city_id' => '312', 'nama_cities' => 'Bogor'],
            ['province_id' => '12','city_id' => '322', 'nama_cities' => 'Cimahi'],
            ['province_id' => '12','city_id' => '332', 'nama_cities' => 'Cirebon'],
            ['province_id' => '12','city_id' => '342', 'nama_cities' => 'Depok'],
            ['province_id' => '12','city_id' => '352', 'nama_cities' => 'Sukabumi'],
            ['province_id' => '12','city_id' => '362', 'nama_cities' => 'Tasikmalaya'],
            ['province_id' => '12','city_id' => '372', 'nama_cities' => 'Banjar'],
            ['province_id' => '13','city_id' => '33', 'nama_cities' => 'Magelang'],
            ['province_id' => '13','city_id' => '303', 'nama_cities' => 'Pekalongan'],
            ['province_id' => '13','city_id' => '313', 'nama_cities' => 'Salatiga'],
            ['province_id' => '13','city_id' => '323', 'nama_cities' => 'Semarang'],
            ['province_id' => '13','city_id' => '333', 'nama_cities' => 'Surakarta'],
            ['province_id' => '13','city_id' => '343', 'nama_cities' => 'Tegal'],
            ['province_id' => '15','city_id' => '35', 'nama_cities' => 'Batu'],
            ['province_id' => '15','city_id' => '305', 'nama_cities' => 'Blitar'],
            ['province_id' => '15','city_id' => '315', 'nama_cities' => 'Kediri'],
            ['province_id' => '15','city_id' => '325', 'nama_cities' => 'Madiun'],
            ['province_id' => '15','city_id' => '335', 'nama_cities' => 'Malang'],
            ['province_id' => '15','city_id' => '345', 'nama_cities' => 'Mojokerto'],
            ['province_id' => '15','city_id' => '355', 'nama_cities' => 'Pasuruan'],
            ['province_id' => '15','city_id' => '365', 'nama_cities' => 'Probolinggo'],
            ['province_id' => '15','city_id' => '375', 'nama_cities' => 'Surabaya'],
            ['province_id' => '15','city_id' => '385', 'nama_cities' => 'Magetan'],
            ['province_id' => '20','city_id' => '61', 'nama_cities' => 'Pontianak'],
            ['province_id' => '20','city_id' => '601', 'nama_cities' => 'Singkawang'],
            ['province_id' => '22','city_id' => '63', 'nama_cities' => 'Banjarbaru'],
            ['province_id' => '22','city_id' => '603', 'nama_cities' => 'Banjarmasin'],
            ['province_id' => '21','city_id' => '62', 'nama_cities' => 'Palangkaraya'],
            ['province_id' => '23','city_id' => '64', 'nama_cities' => 'Balikpapan'],
            ['province_id' => '23','city_id' => '604', 'nama_cities' => 'Bontang'],
            ['province_id' => '23','city_id' => '614', 'nama_cities' => 'Samarinda'],
            ['province_id' => '24','city_id' => '65', 'nama_cities' => 'Tarakan'],
            ['province_id' => '10','city_id' => '21', 'nama_cities' => 'Batam'],
            ['province_id' => '10','city_id' => '201', 'nama_cities' => 'Tanjungpinang'],
            ['province_id' => '8','city_id' => '18', 'nama_cities' => 'Bandar Lampung'],
            ['province_id' => '8','city_id' => '108', 'nama_cities' => 'Metro'],
            ['province_id' => '32','city_id' => '82', 'nama_cities' => 'Ternate'],
            ['province_id' => '32','city_id' => '802', 'nama_cities' => 'Tidoro Kepulauan'],
            ['province_id' => '31','city_id' => '81', 'nama_cities' => 'Ambon'],
            ['province_id' => '31','city_id' => '801', 'nama_cities' => 'Tual'],
            ['province_id' => '18','city_id' => '52', 'nama_cities' => 'Bima'],
            ['province_id' => '18','city_id' => '502', 'nama_cities' => 'Mataram'],
            ['province_id' => '19','city_id' => '53', 'nama_cities' => 'Kupang'],
            ['province_id' => '34','city_id' => '92', 'nama_cities' => 'Sorong'],
            ['province_id' => '33','city_id' => '91', 'nama_cities' => 'Jayapura'],
            ['province_id' => '4','city_id' => '104', 'nama_cities' => 'Dumai'],
            ['province_id' => '4','city_id' => '114', 'nama_cities' => 'Pekanbaru'],
            ['province_id' => '27','city_id' => '73', 'nama_cities' => 'Makassar'],
            ['province_id' => '27','city_id' => '703', 'nama_cities' => 'Palopo'],
            ['province_id' => '27','city_id' => '713', 'nama_cities' => 'Parepare'],
            ['province_id' => '26','city_id' => '72', 'nama_cities' => 'Palu'],
            ['province_id' => '28','city_id' => '74', 'nama_cities' => 'Baubau'],
            ['province_id' => '28','city_id' => '704', 'nama_cities' => 'Kendari'],
            ['province_id' => '25','city_id' => '71', 'nama_cities' => 'Bitung'],
            ['province_id' => '25','city_id' => '701', 'nama_cities' => 'Kotamobagu'],
            ['province_id' => '25','city_id' => '711', 'nama_cities' => 'Manado'],
            ['province_id' => '25','city_id' => '721', 'nama_cities' => 'Tomohon'],
            ['province_id' => '3','city_id' => '103', 'nama_cities' => 'Bukittinggi'],
            ['province_id' => '3','city_id' => '113', 'nama_cities' => 'Padang'],
            ['province_id' => '3','city_id' => '123', 'nama_cities' => 'Padang Panjang'],
            ['province_id' => '3','city_id' => '133', 'nama_cities' => 'Pariaman'],
            ['province_id' => '3','city_id' => '143', 'nama_cities' => 'Sawahlunto'],
            ['province_id' => '3','city_id' => '153', 'nama_cities' => 'Solok'],
            ['province_id' => '6','city_id' => '16', 'nama_cities' => 'Lubuklinggau'],
            ['province_id' => '6','city_id' => '106', 'nama_cities' => 'Pagar Alam'],
            ['province_id' => '6','city_id' => '116', 'nama_cities' => 'Palembang'],
            ['province_id' => '6','city_id' => '126', 'nama_cities' => 'Prabumulih'],
            ['province_id' => '6','city_id' => '136', 'nama_cities' => 'Sekayu'],
            ['province_id' => '2','city_id' => '102', 'nama_cities' => 'Binjai'],
            ['province_id' => '2','city_id' => '112', 'nama_cities' => 'Gunungsitoli'],
            ['province_id' => '2','city_id' => '122', 'nama_cities' => 'Medan'],
            ['province_id' => '2','city_id' => '132', 'nama_cities' => 'Padang Sidempuan'],
            ['province_id' => '2','city_id' => '142', 'nama_cities' => 'Pematangsiantar'],
            ['province_id' => '2','city_id' => '152', 'nama_cities' => 'Sibolga'],
            ['province_id' => '2','city_id' => '162', 'nama_cities' => 'Tanjungbalai'],
            ['province_id' => '2','city_id' => '172', 'nama_cities' => 'Tebing Tinggi'],
        ];
        City::insert($data);
    }
}


